# Generated by Django 5.1.5 on 2025-08-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
